# Generated by Django 4.2.10 on 2024-03-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('mode_of_contact', models.CharField(choices=[('email', 'E-Mail'), ('phone', 'Phone')], default='email', max_length=50, verbose_name='Contact by')),
                ('question_categories', models.CharField(choices=[('post_a_blog', 'Post A Blog'), ('issue_with_profile', 'Issue With Profile'), ('recommendations', 'Recommendations'), ('other', 'Other')], default='post_a_blog', max_length=50, verbose_name='How are we able to help you?')),
                ('message', models.TextField(max_length=3000)),
            ],
        ),
    ]
